config/routes.rb
# typed: false
Rails.application.routes.draw do
  resource :sessions, only: %i[new] do
    get 'auth', on: :member
  end
  resources :builds, only: %i[new create] do
    scope module: :builds do
      resource :minimum_supported_version, only: :update
    end
  end
  get '/builds/:signed_build_id/package', to: 'builds/packages#show', as: :build_package
  resources :internal_builds, only: %i[index]
  resources :enqueues, only: %i[create]
  resources :devices, only: %i[index]
  resources :fetches, only: %i[create]
  resources :deploys, only: %i[destroy]
  root to: 'builds#index'

  namespace :api, defaults: { format: :json }, constraints: lambda { |req| req.format == :json } do
    resources :builds, only: %i[create]
    namespace :builds do
      resource :recommended_versions, only: :show, constraints: { format: 'json' }
    end
  end
end

app/models/build.rb
# typed: false

require 'cfpropertybundle'

# A single build includes the package file to send to the devices.
class Build < ActiveRecord::Base
  has_one_attached :package
  has_one_attached :manifest
  validates :package, presence: true

  has_one :deploy, dependent: :destroy

  scope :external, -> { where.not(deploy_at: nil) }
  scope :internal, -> { where(deploy_at: nil) }
  scope :latest_deployed, lambda {
    joins(:deploy).where(deploys: { status: %i[enqueued running successful] }).order(deploy_at: :desc)
  }

  scope :with_attachments, -> { with_attached_package.with_attached_manifest }

  with_options if: -> { package.attached? } do
    before_validation :set_version, on: :create
    validates :version, uniqueness: true
  end

  attr_accessor :deploy_date, :deploy_time

  validate on: :create do
    validate_future_date if deploy_date.present?
    validate_future_time if deploy_time.present?
  end

  before_create :set_deploy_at, if: -> { deploy_date.present? && deploy_time.present? }
  before_create :create_deploy, if: :external?

  after_create_commit prepend: true do
    GenerateManifestJob.perform_later self
  end

  after_update :handle_new_minimum_supported_version,
               if: -> { minimum_supported_version && saved_change_to_minimum_supported_version? }

  MANIFEST_EXPIRES_IN = 1.week

  def with_valid_manifest?
    manifest.attached? && (manifest.attachment.created_at + MANIFEST_EXPIRES_IN).future?
  end

  def external?
    deploy_at.present?
  end

  def error_message
    errors.full_messages.to_sentence
  end

private

  def set_version
    file = attachment_changes['package'].attachable
    metadata = CFPropertyBundle.new(file).metadata
    self.version = metadata[:bundle_version]
  rescue CFPropertyBundle::Error
    errors.add(:version, :invalid, message: 'cannot be extracted from the attachment')
  end

  def validate_future_date
    self.deploy_date = Date.strptime deploy_date, '%Y-%m-%d'
    errors.add :deploy_date, 'must be in the future' if deploy_date < Time.zone.today
  rescue ArgumentError
    errors.add :deploy_date, 'has an invalid format'
  end

  def validate_future_time
    self.deploy_time = Time.zone.strptime deploy_time, '%H:%M'
    errors.add :deploy_time, 'must be in the future' if deploy_date == Time.zone.today && deploy_time < Time.zone.now
  rescue ArgumentError
    errors.add :deploy_time, 'has an invalid format'
  end

  def set_deploy_at
    self.deploy_at ||= deploy_date + deploy_time.seconds_since_midnight.seconds
  end

  def create_deploy
    self.deploy = Deploy.new
  end

  def handle_new_minimum_supported_version
    Build.where.not(id: id).where(minimum_supported_version: true).update_all(minimum_supported_version: false)
  end
end

app/controllers/api/builds/recommended_versions_controller.rb
# typed: true

module API
  module Builds
    # Exposes an endpoint for third-party APIs to see the recommended build version.
    class RecommendedVersionsController < BaseController
      def show
        render(
          json: {
            current_version: latest_build&.version,
            minimum_supported_version: minimum_supported_build.version,
            manifest_url: manifest_url
          },
          status: :ok
        )
      end

    private

      def latest_build
        @latest_build ||= Build.latest_deployed.first
      end

      def minimum_supported_build
        Build.find_by(minimum_supported_version: true)
      end

      def manifest_url
        latest_build ? helpers.manifest_url(latest_build.manifest) : nil
      end
    end
  end
end

app/controllers/api/builds_controller.rb
# typed: false

module API
  # Exposes an endpoint for third-party APIs to create internal builds.
  class BuildsController < BaseController
    def create
      build = Build.new(build_params)

      if build.save
        head :created
      else
        render json: { message: build.error_message }, status: :bad_request
      end
    end

  private

    def build_params
      params.require(:build).permit :package
    end
  end
end

app/controllers/builds/minimum_supported_versions_controller.rb
# typed: true

module Builds
  # Controller to handle setting the build that is the minimum supported version.
  class MinimumSupportedVersionsController < ApplicationController
    before_action :require_authentication

    # /builds/:id/minimum_supported_version
    def update
      Build.find(params[:build_id]).update!(minimum_supported_version: true)
      redirect_back fallback_location: root_path, notice: 'New minimum supported version.'
    end
  end
end

app/controllers/builds/package_controller.rb
module Builds
  # Redirects to the approriate package to avoid expiration issues
  class PackageController < ApplicationController
    def show
      @build = Build.find_signed(params[:signed_build_id])
      redirect_to(@build.package.service_url)
    end
  end
end

app/controllers/builds_controller.rb
# typed: false

# Displays the latest external builds and shows a form to create new ones.
class BuildsController < ApplicationController
  before_action :require_authentication

  def index
    @builds = Build.external.with_attachments.includes(:deploy).order(deploy_at: :desc)
  end

  def new
    @build = Build.new(deploy_date: Date.tomorrow, deploy_time: Time.strptime('20:00', '%H:%M'))
  end

  def create
    @build = Build.new(build_params)
    @build.deploy_date = @build.deploy_date
    @build.deploy_time = @build.deploy_time

    if @build.save
      redirect_to @build.external? ? root_url : internal_builds_url
    else
      render :new
    end
  end

private

  def build_params
    params.require(:build).permit :deploy_date, :deploy_time, :package
  end
end

app/views/builds/index.html.erb
<% content_for(:refresh) { refresh_button_to 'Enqueue pending', enqueues_path } %>
<table class="table table-sm text-center">
  <thead>
    <tr>
      <th>Version</th>
      <th>Deploy</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr class="table-default text-center">
        <td><%= build.version %></td>
        <td>
          on <%= l build.deploy_at.in_time_zone, format: :verbose %>
        </td>
        <td></td>
        <td>
          <% if build.with_valid_manifest? %>
            <%= link_to 'Install', manifest_url(build.manifest), class: "btn btn-link" %>
          <% else %>
            <%= link_to 'Download', rails_blob_url(build.package, disposition: 'attachment') %>
          <% end %>
          <% if build.minimum_supported_version %>
            Minimum Supported Version
          <% else %>
            <span class="d-inline-block">
              <%= button_to 'Set As Minimum Supported', build_minimum_supported_version_url(build_id: build.id), method: :put, remote: false, class: "btn btn-primary" %>
            </span>
          <% end %>
        </td>
      </tr>
      <tr class="<%= table_class_for(build.deploy) %>">
        <td></td>
        <td>Deploy #<%= build.deploy.id %></td>
        <td><%= build.deploy.status %></td>
        <% if build.deploy.scheduled? %>
        <td><%= cancel_deploy_button(build.deploy.id) %></td>
        <% else %>
        <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/builds/new.html.erb
<%= form_with(model: @build) do |form| %>
  <%= fieldset "1. Choose a file to upload for #{ENV['MDMA_APP_IDENTIFIER']}" do %>
    <div class="form-group">
      <%= form.label :package, 'Choose the .ipa package for this build:', class: 'sr-only' %>
      <% with_errors_on @build, :package, :version do |field_options = {}| %>
        <%= form.file_field :package, field_options %>
      <% end %>
    </div>
  <% end %>

  <%= fieldset "2. For external builds only, choose a date and time to deploy in #{Time.zone.name}" do %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :deploy_date, class: 'sr-only' %>
        <% with_errors_on @build, :deploy_date do |field_options = {}| %>
          <%= form.date_field :deploy_date, field_options %>
        <% end %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :deploy_time, class: 'sr-only' %>
        <% with_errors_on @build, :deploy_time do |field_options = {}| %>
          <%= form.time_field :deploy_time, field_options %>
        <% end %>
      </div>
    </div>
  <% end %>

  <hr />
  <button type="submit" class="btn btn-primary">Upload and deploy</button>
<% end %>