config/routes.rb
# typed: false
Rails.application.routes.draw do
  resource :sessions, only: %i[new] do
    get 'auth', on: :member
  end
  resources :builds, only: %i[new create] do
    scope module: :builds do
      resource :minimum_supported_version, only: :update
    end
  end
  get '/builds/:signed_build_id/package', to: 'builds/packages#show', as: :build_package
  resources :internal_builds, only: %i[index]
  resources :enqueues, only: %i[create]
  resources :devices, only: %i[index]
  resources :fetches, only: %i[create]
  resources :deploys, only: %i[destroy]
  root to: 'builds#index'

  namespace :api, defaults: { format: :json }, constraints: lambda { |req| req.format == :json } do
    resources :builds, only: %i[create]
    namespace :builds do
      resource :recommended_versions, only: :show, constraints: { format: 'json' }
    end
  end
end

app/views/timeslots/show.html.erb
<% content_for(:refresh) { refresh_button_to 'Refresh devices', fetches_path } %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Devices starting with <%= @timeslot.prefixes.to_sentence %></th>
      <th scope="col">Installed version</th>
      <th scope="col">Expected version</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @timeslot.devices.order(:name).each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.app_version %></td>
        <td><%= @timeslot.expected_version %></td>
        <td><%= push_app_button_to device, disabled: (device.app_version == @timeslot.expected_version) %></td>
      </tr>
    <% end %>
  </tbody>
</table>