config/routes.rb
# typed: false
Rails.application.routes.draw do
  resource :sessions, only: %i[new] do
    get 'auth', on: :member
  end
  resources :builds, only: %i[new create] do
    scope module: :builds do
      resource :minimum_supported_version, only: :update
    end
  end
  get '/builds/:signed_build_id/package', to: 'builds/packages#show', as: :build_package
  resources :internal_builds, only: %i[index]
  resources :enqueues, only: %i[create]
  resources :devices, only: %i[index]
  resources :fetches, only: %i[create]
  resources :deploys, only: %i[destroy]
  root to: 'builds#index'

  namespace :api, defaults: { format: :json }, constraints: lambda { |req| req.format == :json } do
    resources :builds, only: %i[create]
    namespace :builds do
      resource :recommended_versions, only: :show, constraints: { format: 'json' }
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Clutter - MDMA</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.4/css/all.css">
  <style>
    .navbar-light .navbar-nav .nav-link { color: #004085 }
    .navbar-light .navbar-nav .active .nav-link { color: #007bff }
  </style>
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.1.1/turbolinks.js"></script>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <span class="navbar-brand">
        <%= navbar_brand %>
      </span>
      <% if logged_in? %>
        <ul class="navbar-nav mr-auto">
          <%= nav_link_to 'External builds', root_path, icon: 'truck' %>
          <%= nav_link_to 'Internal builds', internal_builds_path, icon: 'wrench' %>
          <%= nav_link_to 'Devices', devices_path, icon: 'mobile' %>
          <%= nav_link_to 'Upload new build', new_build_path, icon: 'cloud-upload-alt' %>
        </ul>
        <%= yield :refresh %>
      <% end %>
    </nav>
    <%= yield %>
  </div>
</body>
</html>